### ISSUE TITLE
Import CSV with m2m fields as IDs

### ISSUE THREAD

**Issue by kevinharvey** [storyandstructure/django-nomnom#19]

**Comment by kevinharvey** [comment]
Here's your target file: https://github.com/storyandstructure/django-nomnom/blob/master/nomnom/tests/files/groups_with_perms.csv

**Comment by kdonaldson** [comment]
Serializing the Groups model presents an interesting challenge.  Permissions are created with different IDs each time you install a project with syncdb, it's not possible to use fixtures to freeze usergroup permission. 

It looks like we'll need to get the model to spit out natural keys ...

**Natural keys in fixtures**
Fixtures can refer to remote objects using Natural keys. This lookup scheme is an alternative to the normal primary-key based object references in a fixture, improving readability, and resolving problems referring to objects whose primary key value may not be predictable or known.

https://docs.djangoproject.com/en/dev/topics/serialization/#topics-serialization-natural-keys

**Comment by kdonaldson** [comment]
rough pseudo code ...
- create a copy of kwargs
- if a field in kwargs is an m2m field get rid of it
- create the model instance
- create the foreign key on the model instance 

something like this ...

from django.contrib.auth.models import Group
g1 = groups(name="Group 1")
g1.save()
*g1.permissions = [permission_list]
*g1.permissions.add(permission, permission, ...)
*g1.permissions.remove(permission, permission, ...)
*g1.permissions.clear()

https://docs.djangoproject.com/en/dev/ref/contrib/auth/#django.contrib.auth.models.Permission
